# Generated by Django 3.0.4 on 2022-02-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=15)),
                ('details', models.TextField()),
                ('visitingHour', models.CharField(max_length=15)),
                ('visitingDates', models.TextField()),
                ('dailyoccupation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=None, null=True)),
                ('phone', models.TextField()),
                ('doctors', models.ManyToManyField(to='users.Doctor')),
            ],
        ),
    ]
